apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
spec:
  project: default
  source:
    repoURL: https://github.com/devops491/Jenkins-Zero-To-Hero.git
    targetRevision: main
    path: java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
